# DVC Pipeline Definition
stages:
  download_data:
    cmd: python scripts/download_data.py
    params:
      - data_mode
    deps:
      - scripts/download_data.py
    outs:
      - data/contracts.csv
      - data/mi.csv
      - data/reg_key_pairs.csv

  combine_data:
    cmd: python scripts/combine_data.py
    params:
      - data_mode
    deps:
      - scripts/combine_data.py
      - utils.py
      - data/contracts.csv
      - data/mi.csv
      - data/reg_key_pairs.csv
    outs:
      - data/combined.csv
      - data/unmatched_mi.csv

  summarise_data:
    cmd: python scripts/summarise_data.py
    params:
      - data_mode
    deps:
      - scripts/summarise_data.py
      - data/contracts.csv
      - data/combined.csv
      - data/unmatched_mi.csv
    outs:
      - data/summary_stats.csv
      - data/line_level.csv